Update Cohort Duration
nodejs/mentorship pull request #111
Opened 2018-11-28 17:46 UTC by Bamieh

Update Cohort Duration to 10 weeks (2 and a half months) instead of 6 months.

2018-11-28 22:58 UTC, detrohutt approved these changes
I think we still need to discuss how or if we will perform kickoff meetings moving forwards, but this all looks good in the meantime!

2019-01-25 16:53 UTC, dshaw approved these changes
Let's align and land in today's (2019-01-25) meeting.

2019-01-25 17:50 UTC, dshaw requested changes
Please change 10 weeks to 2.5 months.

2019-01-25 17:50 UTC, dshaw commented on README.md
> +The mentorship duration will be 10 weeks, during which the mentor will provide
```suggestion
The mentorship duration will be 10 weeks (2.5 months), during which the mentor will provide
```

2019-01-25 18:26 UTC, merged